<?xml version="1.0" ?>
<testsuite name="FrontendBackendCheckTestCase-20230812165925" tests="1" time="0.037" failures="0" errors="1">
	<testcase classname="FrontendBackendCheckTestCase" name="test_frontend_backend" time="0.037">
		<error type="WebDriverException" message="Message: Unable to find handler for (POST) //session
"><![CDATA[Traceback (most recent call last):
  File "C:\Users\wadem\Documents\TastyRepos\tastybackend\stagingtest\test_staging.py", line 70, in setUp
    driver = webdriver.Remote(
  File "C:\Users\wadem\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 206, in __init__
    self.start_session(capabilities)
  File "C:\Users\wadem\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 290, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "C:\Users\wadem\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 345, in execute
    self.error_handler.check_response(response)
  File "C:\Users\wadem\anaconda3\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Unable to find handler for (POST) //session

]]></error>
	</testcase>
	<system-out><![CDATA[]]></system-out>
	<system-err><![CDATA[]]></system-err>
</testsuite>
